language: python
before_install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
install:
  - pip install Flask
script:
  - skip
deploy:
  provider: heroku
  api_key:
    secure: e016c947-2cb6-4f3e-a6b9-9dfb259c21ff